# Generated by Django 5.1.3 on 2024-11-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
