# Generated by Django 5.1.3 on 2024-11-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userapp_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='point',
            field=models.IntegerField(default=500),
        ),
    ]
